/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocadmus;

import com.placeholder.PlaceHolder;

import conexion.JDBC;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renatasanandres
 */
public class Bill extends javax.swing.JFrame {

	/**
	 * Creates new form Facture
	 */
	
	String idFactura;
	String idCliente;
	
	
	public Bill(String id) {
		idFactura = id;
		initComponents();
		bill.setBackground(new Color(255,255,255,150));
		PlaceHolder holder1 = new PlaceHolder(user,"Reciever");
		PlaceHolder holder2 = new PlaceHolder(destination,"Destination Address");

		
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		bill = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		date = new javax.swing.JLabel();
		name = new javax.swing.JLabel();
		id = new javax.swing.JLabel();
		phone = new javax.swing.JLabel();
		address = new javax.swing.JLabel();
		buy = new javax.swing.JButton();
		billT = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		destination = new javax.swing.JTextField();
		user = new javax.swing.JTextField();
		home = new javax.swing.JButton();
		bgOrder = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill2.png"))); // NOI18N
		getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

		bill.setBackground(new java.awt.Color(255, 255, 255));
		bill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/date.png"))); // NOI18N
		bill.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 110, -1, 35));

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/name.png"))); // NOI18N
		bill.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 460, -1, 35));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usern.png"))); // NOI18N
		bill.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 190, -1, 35));

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phone.png"))); // NOI18N
		bill.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 230, -1, 35));

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/address.png"))); // NOI18N
		bill.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 510, -1, 35));
		bill.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 113, 350, 30));
		bill.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 153, 350, 30));
		bill.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 193, 350, 30));
		bill.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 233, 350, 30));
		bill.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 273, 350, 30));

		buy.setBackground(new java.awt.Color(9, 20, 104));
		buy.setFont(new java.awt.Font("PT Mono", 0, 18)); // NOI18N
		buy.setText("ACCEPT");
		buy.setAlignmentY(0.0F);
		buy.setContentAreaFilled(false);
		buy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		buy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		buy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buyActionPerformed(evt);
				
				System.out.println("Buy button pressed");
				
				conexion.openConection();

				try {

					conexion.setStmt(conexion.getConn().createStatement());
					ResultSet rs = conexion.getStmt().executeQuery("SELECT `LUGARGEO_idLUGARGEO` FROM `CLIENTE` WHERE `id` = " + idCliente + ";");
					System.out.println("SELECT `LUGARGEO_idLUGARGEO` FROM `CLIENTE` WHERE `id` = " + idCliente + ";");
					rs.next();
					
					String idLugarGeo = rs.getString("LUGARGEO_idLUGARGEO");
					
					conexion.setStmt(conexion.getConn().createStatement());
					conexion.getStmt().executeQuery("INSERT INTO `ALBARAN` (`nombreDest`, `LUGARGEO_idLUGARGEO`) VALUES ('" + user.getText() + "', " + idLugarGeo + ");");
					System.out.println("INSERT INTO `ALBARAN` (`fechaEntrega`, `nombreDest`, `LUGARGEO_idLUGARGEO`) VALUES (CURDATE(), '" + user.getText() + "', " + idLugarGeo + ");");
					
					//Create pedido
					
					conexion.setStmt(conexion.getConn().createStatement());
					rs = conexion.getStmt().executeQuery("INSERT INTO `PEDIDO` (`fechaPed`, estado, `FACTURA_idFACTURA`) VALUES (CURDATE(), 'Aceptado', " + idFactura + ");");
					System.out.println("INSERT INTO `PEDIDO` (`fechaPed`, estado, `FACTURA_idFACTURA`, `FACTURA_CLIENTE_idCLIENTE`) VALUES (CURDATE(), 'Aceptado', " + idFactura + "," + idCliente + ");");
					
					//Update Stock quantity
					//conexion.setStmt(conexion.getConn().createStatement());
					//rs = conexion.getStmt().executeQuery("UPDATE `PRODUCTO` SET `cantidadStock` = 30 WHERE `nombreProducto` = 'Weed';");
					
					
					
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				conexion.closeConection();
				
			}
		});
		bill.add(buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 600, 350, 45));

		billT.setViewportView(jTable1);

		bill.add(billT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 420, 140));

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/name.png"))); // NOI18N
		bill.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 150, -1, 35));

		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/address.png"))); // NOI18N
		bill.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 270, -1, 35));
		bill.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 513, 350, 30));
		bill.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 463, 200, 30));

		getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 460, 650));

		home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
		home.setBorder(null);
		home.setBorderPainted(false);
		home.setContentAreaFilled(false);
		home.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				homeActionPerformed(evt);
			}
		});
		getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 90));

		bgOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg2.jpg"))); // NOI18N
		getContentPane().add(bgOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 800));

		pack();
		
		//CODE
				conexion.openConection();

				try {

					conexion.setStmt(conexion.getConn().createStatement());
					ResultSet rs = conexion.getStmt().executeQuery("SELECT `fechaFac`, `nombreCli`,  id, telefono, direccion FROM `FACTURA`, `CLIENTE`, `LUGARGEO` WHERE `CLIENTE_idCLIENTE` = `idCLIENTE` AND CLIENTE.LUGARGEO_idLUGARGEO = `idLUGARGEO` AND `idFACTURA` = " + idFactura + ";");
					System.out.println("SELECT `fechaFac`, `nombreCli`,  id, telefono, direccion FROM `FACTURA`, `CLIENTE`, `LUGARGEO` WHERE `CLIENTE_idCLIENTE` = `idCLIENTE` AND CLIENTE.LUGARGEO_idLUGARGEO = `idLUGARGEO` AND `idFACTURA` = " + idFactura + ";");
					
					rs.next();
					
					date.setText(rs.getString("fechaFac"));
					name.setText(rs.getString("nombreCli"));
					id.setText(rs.getString("id"));
					idCliente = id.getText();
					phone.setText(rs.getString("telefono"));
					address.setText(rs.getString("direccion"));
					
					
					
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				conexion.closeConection();
				
				retrieveTable2();
				
				//CODE
		
	}// </editor-fold>//GEN-END:initComponents

	private void retrieveTable2() {

		conexion.openConection();

		System.out.println("Creating Statement");

		try {

			conexion.setStmt(conexion.getConn().createStatement());

			ResultSet rs = conexion.getStmt().executeQuery("SELECT `nombreProducto` AS Producto, cantidad AS Cantidad, subtotal as Subtotal  FROM `DETALLE`, `PRODUCTO` WHERE `PRODUCTO_idPRODUCTO` = `idPRODUCTO` AND `FACTURA_idFACTURA` = " + idFactura + ";");
			System.out.println("SELECT `nombreProducto` AS Producto, cantidad AS Cantidad, subtotal as Subtotal  FROM `DETALLE`, `PRODUCTO` WHERE `PRODUCTO_idPRODUCTO` = `idPRODUCTO` AND `FACTURA_idFACTURA` = " + idFactura + ";");
			ResultSetMetaData metaData = rs.getMetaData();

			int numberOfColumns = metaData.getColumnCount();
			Vector<String> columnames = new Vector<String>();

			for(int column = 0 ; column < numberOfColumns ; column++)
				columnames.addElement(metaData.getColumnLabel(column + 1));

			Vector<Object> rows = new Vector<Object>();

			while(rs.next()) {

				Vector<String> newRow = new Vector<String>();

				for(int i = 1 ; i <= numberOfColumns; i++)
					newRow.addElement(rs.getString(i));

				rows.addElement(newRow);

			}

			jTable1.setModel(new DefaultTableModel(rows, columnames));


		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		conexion.closeConection();


	}

	
	private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed

	}//GEN-LAST:event_buyActionPerformed

	private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
		CustomerMain main = new CustomerMain();
		main.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_homeActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Bill("id").setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel address;
	private javax.swing.JLabel bgOrder;
	private javax.swing.JPanel bill;
	private javax.swing.JScrollPane billT;
	private javax.swing.JButton buy;
	private javax.swing.JLabel date;
	private javax.swing.JTextField destination;
	private javax.swing.JButton home;
	private javax.swing.JLabel id;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JTable jTable1;
	private javax.swing.JLabel name;
	private javax.swing.JLabel phone;
	private javax.swing.JTextField user;

	private JDBC conexion = new JDBC();
	// End of variables declaration//GEN-END:variables
}
