/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocadmus;

/**
 *
 * @author renatasanandres
 */
public class CustomerMain extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMain
     */
    public CustomerMain() {
        initComponents();
    }

    public void logOut(){
        Customer customer=new Customer();
        customer.setVisible(true);
        this.dispose();
    }
    
    public void home(){
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finder = new javax.swing.JTextField();
        FIND = new javax.swing.JButton();
        finderT = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        quantity = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        home2 = new javax.swing.JButton();
        logOut2 = new javax.swing.JButton();
        bgOrder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finder.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(finder, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 550, 50));

        FIND.setBackground(new java.awt.Color(255, 255, 255));
        FIND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        FIND.setBorder(null);
        FIND.setBorderPainted(false);
        FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINDActionPerformed(evt);
            }
        });
        getContentPane().add(FIND, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 20, 70, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        finderT.setViewportView(jTable1);

        getContentPane().add(finderT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 900, 520));

        quantity.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 700, 170, 40));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setText("CART");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 700, 100, 40));

        checkOut.setBackground(new java.awt.Color(255, 255, 255));
        checkOut.setText("CHECK OUT");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        getContentPane().add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 700, 140, 50));

        home2.setBackground(new java.awt.Color(255, 255, 255));
        home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        home2.setToolTipText("");
        home2.setBorder(null);
        home2.setBorderPainted(false);
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        getContentPane().add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 50, 50));

        logOut2.setBackground(new java.awt.Color(255, 255, 255));
        logOut2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        logOut2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logOut2.setText("LOG OUT");
        logOut2.setToolTipText("");
        logOut2.setAlignmentY(0.0F);
        logOut2.setBorder(null);
        logOut2.setBorderPainted(false);
        logOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut2ActionPerformed(evt);
            }
        });
        getContentPane().add(logOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        bgOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg2.jpg"))); // NOI18N
        getContentPane().add(bgOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        Bill bill = new Bill();
        bill.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkOutActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void FINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FINDActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        home();
    }//GEN-LAST:event_home2ActionPerformed

    private void logOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut2ActionPerformed
        logOut();
    }//GEN-LAST:event_logOut2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FIND;
    private javax.swing.JButton add;
    private javax.swing.JLabel bgOrder;
    private javax.swing.JButton checkOut;
    private javax.swing.JTextField finder;
    private javax.swing.JScrollPane finderT;
    private javax.swing.JButton home2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logOut2;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
