/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocadmus;

/**
 *
 * @author renatasanandres
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Clog = new javax.swing.JButton();
        Stlog = new javax.swing.JButton();
        Cimg = new javax.swing.JLabel();
        Simg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clog.setBackground(new java.awt.Color(255, 255, 255));
        Clog.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        Clog.setText("Customer Log In");
        Clog.setToolTipText("");
        Clog.setAlignmentY(0.0F);
        Clog.setBorder(null);
        Clog.setBorderPainted(false);
        Clog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClogActionPerformed(evt);
            }
        });
        getContentPane().add(Clog, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 160, 50));

        Stlog.setBackground(new java.awt.Color(255, 255, 255));
        Stlog.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        Stlog.setText("Stuff Log In");
        Stlog.setToolTipText("");
        Stlog.setAlignmentY(0.0F);
        Stlog.setBorderPainted(false);
        Stlog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stlog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Stlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StlogActionPerformed(evt);
            }
        });
        getContentPane().add(Stlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 160, 50));

        Cimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer-people-730x449.png"))); // NOI18N
        getContentPane().add(Cimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        Simg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff.jpg"))); // NOI18N
        getContentPane().add(Simg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 370, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClogActionPerformed
        Customer customer = new Customer();
        customer.setVisible(true);
        dispose();
    }//GEN-LAST:event_ClogActionPerformed

    private void StlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StlogActionPerformed
        Staff staff = new Staff();
        staff.setVisible(true);
        dispose();
    }//GEN-LAST:event_StlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cimg;
    private javax.swing.JButton Clog;
    private javax.swing.JLabel Simg;
    private javax.swing.JButton Stlog;
    // End of variables declaration//GEN-END:variables
}
