/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocadmus;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author renatasanandres
 */
public class StaffMain extends javax.swing.JFrame {
    int option;
    JPanel panels[] = new JPanel[4];
    
    /**
     * Creates new form StaffMain
     */
    public StaffMain() {
        initComponents();
        fillarray();
        setFalse();
    }
    
    public void setFalse(){
        for(int i=1;i<panels.length;i++)
            panels[i].setVisible(false);
    }
    
    public void fillarray(){
        panels[1]=this.userdata;
        panels[2]=this.productdata;
        panels[3]=this.orderdata;
    }
    
    public void user(){
        PlaceHolder holder1 = new PlaceHolder(username,"Username");
        PlaceHolder holder2 = new PlaceHolder(password,"Password");
        PlaceHolder holder3 = new PlaceHolder(phone,"Phone");
        PlaceHolder holder4 = new PlaceHolder(name,"Name");
        PlaceHolder holder5 = new PlaceHolder(address,"Address");
    }
    
    public void product(){
        PlaceHolder holder1 = new PlaceHolder(product,"Name Product");
        PlaceHolder holder2 = new PlaceHolder(value,"Value");
        PlaceHolder holder3 = new PlaceHolder(quantity,"Quantity");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        insertar = new javax.swing.JPanel();
        TypeInsert = new javax.swing.JComboBox<>();
        userdata = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        padlock = new javax.swing.JLabel();
        padlock3 = new javax.swing.JLabel();
        padlock4 = new javax.swing.JLabel();
        padlock5 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        bginsert = new javax.swing.JLabel();
        orderdata = new javax.swing.JPanel();
        user2 = new javax.swing.JLabel();
        padlock2 = new javax.swing.JLabel();
        password8 = new javax.swing.JTextField();
        login2 = new javax.swing.JButton();
        username2 = new javax.swing.JTextField();
        password9 = new javax.swing.JTextField();
        password10 = new javax.swing.JTextField();
        password11 = new javax.swing.JTextField();
        productdata = new javax.swing.JPanel();
        user1 = new javax.swing.JLabel();
        padlock1 = new javax.swing.JLabel();
        padlock6 = new javax.swing.JLabel();
        product = new javax.swing.JTextField();
        login1 = new javax.swing.JButton();
        value = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        eliminar = new javax.swing.JPanel();
        TypeDelete = new javax.swing.JComboBox<>();
        bgdelete = new javax.swing.JLabel();
        editar = new javax.swing.JPanel();
        TypeEdit = new javax.swing.JComboBox<>();
        bgedit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeInsert.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        TypeInsert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoger Opción...", "Usuario\t", "Producto\t", "Pedido", " " }));
        TypeInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeInsertActionPerformed(evt);
            }
        });
        insertar.add(TypeInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 40));

        userdata.setBackground(new java.awt.Color(255, 255, 255));
        userdata.setForeground(new java.awt.Color(255, 255, 255));
        userdata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usern.png"))); // NOI18N
        userdata.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 25, 40, 40));

        padlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlocker.png"))); // NOI18N
        userdata.add(padlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        padlock3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phone.png"))); // NOI18N
        userdata.add(padlock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        padlock4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/name.png"))); // NOI18N
        userdata.add(padlock4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        padlock5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/address.png"))); // NOI18N
        userdata.add(padlock5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        password.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        userdata.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 350, 50));

        username.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        userdata.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 350, 50));

        phone.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        userdata.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 350, 50));

        name.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        userdata.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 350, 50));

        address.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        userdata.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 350, 50));

        login.setBackground(new java.awt.Color(9, 20, 104));
        login.setFont(new java.awt.Font("PT Mono", 0, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("REGISTER");
        login.setAlignmentY(0.0F);
        login.setContentAreaFilled(false);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        userdata.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 350, 45));

        insertar.add(userdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 430, 480));

        bginsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ins.jpg"))); // NOI18N
        insertar.add(bginsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 1400, 940));

        orderdata.setBackground(new java.awt.Color(255, 255, 255));
        orderdata.setForeground(new java.awt.Color(255, 255, 255));
        orderdata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usern.png"))); // NOI18N
        orderdata.add(user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 25, 40, 40));

        padlock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlocker.png"))); // NOI18N
        orderdata.add(padlock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        password8.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        password8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password8ActionPerformed(evt);
            }
        });
        orderdata.add(password8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 350, 50));

        login2.setBackground(new java.awt.Color(9, 20, 104));
        login2.setFont(new java.awt.Font("PT Mono", 0, 18)); // NOI18N
        login2.setForeground(new java.awt.Color(255, 255, 255));
        login2.setAlignmentY(0.0F);
        login2.setContentAreaFilled(false);
        login2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login2.setLabel("LOGIN");
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });
        orderdata.add(login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 350, 45));

        username2.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        username2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                username2FocusLost(evt);
            }
        });
        username2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username2ActionPerformed(evt);
            }
        });
        orderdata.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 350, 50));

        password9.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        password9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password9ActionPerformed(evt);
            }
        });
        orderdata.add(password9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 350, 50));

        password10.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        password10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password10ActionPerformed(evt);
            }
        });
        orderdata.add(password10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 350, 50));

        password11.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        password11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password11ActionPerformed(evt);
            }
        });
        orderdata.add(password11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 350, 50));

        insertar.add(orderdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 430, 480));

        productdata.setBackground(new java.awt.Color(255, 255, 255));
        productdata.setForeground(new java.awt.Color(255, 255, 255));
        productdata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        productdata.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 25, 40, 40));

        padlock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quantity.png"))); // NOI18N
        productdata.add(padlock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        padlock6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/value.png"))); // NOI18N
        productdata.add(padlock6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        product.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        productdata.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 350, 50));

        login1.setBackground(new java.awt.Color(9, 20, 104));
        login1.setFont(new java.awt.Font("PT Mono", 0, 18)); // NOI18N
        login1.setForeground(new java.awt.Color(255, 255, 255));
        login1.setText("REGISTER");
        login1.setAlignmentY(0.0F);
        login1.setContentAreaFilled(false);
        login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        productdata.add(login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 350, 45));

        value.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valueFocusLost(evt);
            }
        });
        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });
        productdata.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 350, 50));

        quantity.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        productdata.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 350, 50));

        insertar.add(productdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 430, 310));

        jTabbedPane1.addTab("Insertar", insertar);

        eliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeDelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoger Opción...", "Usuario\t", "Producto\t", "Pedido", " " }));
        TypeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeDeleteActionPerformed(evt);
            }
        });
        eliminar.add(TypeDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        bgdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ins.jpg"))); // NOI18N
        eliminar.add(bgdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Eliminar", eliminar);

        editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoger Opción...", "Usuario\t", "Producto\t", "Pedido", " " }));
        TypeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeEditActionPerformed(evt);
            }
        });
        editar.add(TypeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        bgedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ins.jpg"))); // NOI18N
        editar.add(bgedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Editar", editar);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeInsertActionPerformed
        setFalse();
        option = this.TypeInsert.getSelectedIndex();
        panels[option].setVisible(true);
        panels[option].setBackground(new Color(255,255,255,65));
        panels[option].requestFocus();
        switch (option){
            case 1:
                user();
                break;
            case 2:
                product();
                break;
            case 3:
        }
            
    }//GEN-LAST:event_TypeInsertActionPerformed

    private void TypeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeDeleteActionPerformed

    private void TypeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeEditActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

    }//GEN-LAST:event_loginActionPerformed

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login1ActionPerformed

    private void valueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valueFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_valueFocusLost

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void password8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password8ActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login2ActionPerformed

    private void username2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_username2FocusLost

    private void username2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username2ActionPerformed

    private void password9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password9ActionPerformed

    private void password10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password10ActionPerformed

    private void password11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password11ActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TypeDelete;
    private javax.swing.JComboBox<String> TypeEdit;
    private javax.swing.JComboBox<String> TypeInsert;
    private javax.swing.JTextField address;
    private javax.swing.JLabel bgdelete;
    private javax.swing.JLabel bgedit;
    private javax.swing.JLabel bginsert;
    private javax.swing.JPanel editar;
    private javax.swing.JPanel eliminar;
    private javax.swing.JPanel insertar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton login;
    private javax.swing.JButton login1;
    private javax.swing.JButton login2;
    private javax.swing.JTextField name;
    private javax.swing.JPanel orderdata;
    private javax.swing.JLabel padlock;
    private javax.swing.JLabel padlock1;
    private javax.swing.JLabel padlock2;
    private javax.swing.JLabel padlock3;
    private javax.swing.JLabel padlock4;
    private javax.swing.JLabel padlock5;
    private javax.swing.JLabel padlock6;
    private javax.swing.JTextField password;
    private javax.swing.JTextField password10;
    private javax.swing.JTextField password11;
    private javax.swing.JTextField password8;
    private javax.swing.JTextField password9;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField product;
    private javax.swing.JPanel productdata;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JPanel userdata;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username2;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
