/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocadmus;

import com.placeholder.PlaceHolder;
import conexion.JDBC;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renatasanandres
 */
public class Tracking extends javax.swing.JFrame {
	String ClId;
	/**
	 * Creates new form Tracking
	 */
	public Tracking(String id) {
		ClId = id;
		initComponents();
		PlaceHolder holder = new PlaceHolder(OrderId,"Order Id");
		order.setBackground(new Color(255,255,255,85));
		retrieveTable();
	}


	public void retrieveTable(){
		conexion.openConection();

		System.out.println("Creating Statement");

		try {

			conexion.setStmt(conexion.getConn().createStatement());


			ResultSet rs = conexion.getStmt().executeQuery("SELECT idCLIENTE FROM CLIENTE WHERE id = '" + ClId + "' ");
			System.out.println("SELECT idCLIENTE FROM CLIENTE WHERE id = '" + ClId + "' ");
			rs.next();
			String idCliente = rs.getString("idCLIENTE");


			rs = conexion.getStmt().executeQuery("SELECT idENVIO, nombreProducto, cantidad, ENVIO.estado, fechaEntrega   FROM DETALLE_ENVIO, ENVIO, PEDIDO, FACTURA,CLIENTE  WHERE `idDETALLE_ENVIO`  = idENVIO AND FACTURA_idFACTURA = idFACTURA AND CLIENTE_idCLIENTE = idCLIENTE  AND`CLIENTE_idCLIENTE` = " + idCliente + ";");
			System.out.println("SELECT idENVIO, nombreProducto, cantidad, ENVIO.estado, fechaEntrega   FROM DETALLE_ENVIO, ENVIO, PEDIDO, FACTURA,CLIENTE  WHERE `idDETALLE_ENVIO`  = idENVIO AND FACTURA_idFACTURA = idFACTURA AND CLIENTE_idCLIENTE = idCLIENTE  AND`CLIENTE_idCLIENTE` = " + idCliente + ";");

			ResultSetMetaData metaData = rs.getMetaData();

			int numberOfColumns = metaData.getColumnCount();
			Vector<String> columnames = new Vector<String>();

			for(int column = 0 ; column < numberOfColumns ; column++)
				columnames.addElement(metaData.getColumnLabel(column + 1));

			Vector<Object> rows = new Vector<Object>();

			while(rs.next()) {

				Vector<String> newRow = new Vector<String>();

				for(int i = 1 ; i <= numberOfColumns; i++)
					newRow.addElement(rs.getString(i));

				rows.addElement(newRow);

			}

			jTable1.setModel(new DefaultTableModel(rows, columnames));


		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		conexion.closeConection();


	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		order = new javax.swing.JPanel();
		padlock14 = new javax.swing.JLabel();
		padlock17 = new javax.swing.JLabel();
		OrderId = new javax.swing.JTextField();
		register = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		home = new javax.swing.JButton();
		bg = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		order.setBackground(new java.awt.Color(255, 255, 255));
		order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		padlock14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productE.png"))); // NOI18N
		order.add(padlock14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

		padlock17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
		order.add(padlock17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

		OrderId.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OrderIdActionPerformed(evt);
			}
		});
		order.add(OrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 350, 50));

		register.setBackground(new java.awt.Color(255, 255, 255));
		register.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
		register.setForeground(new java.awt.Color(255, 255, 255));
		register.setText("FIND SHIPPING");
		register.setBorderPainted(false);
		register.setContentAreaFilled(false);
		register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		register.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				registerActionPerformed(evt);
			}
		});
		order.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 350, 45));

		getContentPane().add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 440, 260));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
					{},
					{},
					{},
					{}
				},
				new String [] {

				}
				));
		jScrollPane1.setViewportView(jTable1);

		getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 600, 260));

		home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
		home.setBorder(null);
		home.setBorderPainted(false);
		home.setContentAreaFilled(false);
		home.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				homeActionPerformed(evt);
			}
		});
		getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 90));

		bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg2.jpg"))); // NOI18N
		getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 830));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void OrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderIdActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_OrderIdActionPerformed

	private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

	}//GEN-LAST:event_registerActionPerformed

	private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
		CustomerMain main = new CustomerMain();
		main.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_homeActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Tracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Tracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Tracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Tracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Tracking("id").setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField OrderId;
	private javax.swing.JLabel bg;
	private javax.swing.JButton home;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel order;
	private javax.swing.JLabel padlock14;
	private javax.swing.JLabel padlock17;
	private javax.swing.JButton register;
	// End of variables declaration//GEN-END:variables
	private JDBC conexion= new JDBC();
}
